# ---
- name: Configure JAMQ-7 instance
  when: jamq7_instance_type is defined and jamq7_instance_type != "default"
  template:
    src: templates/{{ jamq7_instance_type }}/broker.xml
    dest: "{{ jamq7_install_dest }}/{{ jamq7_instance_dir }}/etc/broker.xml"
    owner: "{{ jamq7_user }}"
    group: "{{ jamq7_user }}"
    mode: 0755
