---
- name: Ensure Java VM is present {{ jamq7_broker_java }}
  when: jamq7_broker_java is defined and jamq7_broker_java_install is defined and jamq7_broker_java_install == true
  yum: name={{ jamq7_broker_java }} state=present

- name: Create broker instance
  command: "{{ jamq7_instance_create_command }}"
  args:
    chdir: "{{ jamq7_install_dest }}/{{ jamq7_install_link }}/bin"
