---
- name: Create dir for broker instance
  file:
   path: "{{ jamq7_install_dest }}/{{ broker_instance_dir }}"
   state: directory
   mode: 0755
   owner: {{ jamq7_user }}
   group: {{ jamq7_user }}

- name: Create broker instance
  command: runuser -s ${SHELL} jamq -c './artemis create  --force --nio --role=amq --user=admin --require-login --password=admin --java-options="-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port={{ broker_instance_jmx_port }} -Djava.rmi.server.hostname={{ ansible_default_ipv4.address }} -Dcom.sun.management.jmxremote.rmi.port={{ broker_instance_jmx_port }} -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false " --name=amq {{ remote_dest }}/{{ broker_instance_dir }}'
  args:
    chdir: "{{ remote_dest }}/{{ broker_install_dir_link }}/bin"
